stages:
    - build
    - publish

variables:
    GIT_SUBMODULE_STRATEGY: 'recursive'
    DOCKER_DRIVER: overlay2
    CLICKABLE_VERSION: "7.5.0"

.armhf: &armhf
    variables:
        ARCH: "armhf"
        ARCH_TRIPLET: "arm-linux-gnueabihf"

.arm64: &arm64
    variables:
        ARCH: "arm64"
        ARCH_TRIPLET: "aarch64-linux-gnu"

.amd64: &amd64
    variables:
        ARCH: "amd64"
        ARCH_TRIPLET: "x86_64-linux-gnu"

.build:
    image: "clickable/ci-20.04-$ARCH:$CLICKABLE_VERSION"
    stage: build
    script: 'clickable build --clean --arch $ARCH --accept-review-errors'
    artifacts:
        paths:
            - "build/$ARCH_TRIPLET/app"
        expire_in: 1 week

build-armhf:
    <<: *armhf
    extends: .build

build-arm64:
    <<: *arm64
    extends: .build

build-amd64:
    <<: *amd64
    extends: .build

publish:
    stage: publish
    image: "clickable/ci-20.04-armhf:$CLICKABLE_VERSION"
    rules:
        - if: $CI_COMMIT_TAG
    script:
        - 'clickable publish "$CI_COMMIT_MESSAGE"'
        - 'clickable publish --arch arm64'
        - 'clickable publish --arch amd64'
    dependencies:
        - build-armhf
        - build-arm64
        - build-amd64
    artifacts:
        paths:
            - build/arm-linux-gnueabihf/app/*.click
            - build/aarch64-linux-gnu/app/*.click
            - build/x86_64-linux-gnu/app/*.click
        expire_in: 30 days
